POST http://localhost:3002/ HTTP/1.1
content-type: application/json
x-api-key: unvalor

{
    "data": "gustavo"
}

###
GET http://localhost:3002/ HTTP/1.1

###
GET http://localhost:3002/index.html HTTP/1.1

###
GET http://localhost:3002/otro.html HTTP/1.1

###
GET http://localhost:3002/hola HTTP/1.1
content-type: application/json

# Good api key 
###
POST http://localhost:3002/auth/middleware HTTP/1.1
content-type: application/json
x-api-key: 2valor

{
    "role": "admin",
    "data": "some data"
}

# Wrong api key
###
POST http://localhost:3002/auth/middleware HTTP/1.1
content-type: application/json
x-api-key: unvalor

{
    "data": "gustavo"
}

# Wrong role 
###
POST http://localhost:3002/auth/middleware HTTP/1.1
content-type: application/json
x-api-key: 2valor

{
    "data": "gustavo"
}
